apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: qudwndh/jente:1.19 # Flask 애플리케이션과 동일한 이미지 사용
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database_uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: secret_key
        - name: GCS_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: GCS_BUCKET_NAME
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/google-credentials.json"
        - name: CELERY_BROKER_URL
          value: redis://redis:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis:6379/0
        volumeMounts:
        - name: google-credentials
          mountPath: "/etc/secrets"
          readOnly: true
        resources:
          requests:
            memory: "250Mi"
            cpu: "210m"
          limits:
            memory: "280Mi"
            cpu: "220m"
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
